#ifndef __EVENTTYPE_H_
#define __EVENTTYPE_H_

enum EventType
{
    EVENT_GAMEOVER,
    EVENT_PLAYERDEATH,
    EVENT_BOMBEXPLODED,
    EVENT_FIREEXTINGUISHED,
    EVENT_PLAYERFIRECOLLISION,
    EVENT_ENEMYFIRECOLLISION,
    EVENT_ENEMYDESTROY,
    EVENT_POWERUPPICKED
};

#endif //__EVENTTYPE_H_
